name: Deploy Mixify to production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".volta"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build
        env:
          NODE_ENV: production
          VITE_SPOTIFY_CLIENT_ID: ${{ secrets.VITE_SPOTIFY_CLIENT_ID }}
          VITE_SPOTIFY_CLIENT_SECRET: ${{ secrets.VITE_SPOTIFY_CLIENT_SECRET }}
          VITE_SPOTIFY_BASE_API_URL: ${{ secrets.VITE_SPOTIFY_BASE_API_URL }}
          VITE_SPOTIFY_ACCOUNT_API_URL: ${{ secrets.VITE_SPOTIFY_ACCOUNT_API_URL }}
          VITE_AUTH_REDIRECT_URI: ${{ secrets.VITE_AUTH_REDIRECT_URI }}
          VITE_LAST_FM_API_KEY: ${{ secrets.VITE_LAST_FM_API_KEY }}
          VITE_LAST_FM_BASE_API_URL: ${{ secrets.VITE_LAST_FM_BASE_API_URL }}

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=dist --message="Deploy from ${{ github.event.head_commit.message }}"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}